### ISSUE TITLE
Build and call API - Test API Failed ❌

### ISSUE THREAD

**Issue by Harsh-2002** [kylierst/MSO_E5_Dev_AutoRenew#10]
##Test API failed please help me.

<img width="1440" alt="Screenshot 2023-03-25 at 2 55 32 PM" src="https://user-images.githubusercontent.com/65254552/227708936-d42b7e96-1e11-4ac1-a5fb-7b518b4c58f4.png">

And Please help me with this to declare variable.
```
generate three variables for github repository action and set the value as given below
Name: CONFIG_ID value client_id=r'your applcation_id' (within the quotes)
Name: CONFIG_KEY value client_secret=r'your_secret'
Name: REFRESH_TOKEN value refresh_token=r'your_refresh_token'
```

**Comment by kylierst** [comment]
You should create action secrets over here
![image](https://user-images.githubusercontent.com/22324149/227713411-b0d09f09-0e62-4e6e-97b1-4931e8808dd9.png)

**Comment by Harsh-2002** [comment]
I have to give to name like CONFIG_ID and inside i have to put value like this client_id=r'4a1582d3-349d-4c74-bf3e-f025e2fc000b' ..... right ?

Can you write syntax

**Comment by kylierst** [comment]
> I have to give to name like CONFIG_ID and inside i have to put value like this client_id=r'4a1582d3-349d-4c74-bf3e-f025e2fc000b' ..... right ?
> 
> Can you write syntax

Just exactly like that.
