### ISSUE TITLE
Am I doing something wrong

### ISSUE THREAD

**Issue by Shure2005** [kylierst/MSO_E5_Dev_AutoRenew#15]
Image : https://imgur.com/a/4KUYXBM

**Comment by kylierst** [comment]
When did you start using the script? And when did your trial subscription start?

**Comment by Shure2005** [comment]
I started using the script around the 18th of March, and the trial subscription started around the 4th of February

**Comment by thecountrox** [comment]
![image](https://user-images.githubusercontent.com/74064922/230711184-c479f2bd-db2a-4693-b3d2-0955b7201d36.png)
Same here

**Comment by kylierst** [comment]
> I started using the script around the 18th of March, and the trial subscription started around the 4th of February

I didn't received that email in my case, did you make sure that your developer account is linked to your github?

**Comment by jaum20** [comment]
I have the same problem. Did you guys find the cause?

**Comment by dolodi** [comment]
who knows

**Comment by darkdex52** [comment]
Yeah, I'd really like to know what are the options how to check if any of the API calls show up Azure.
