### ISSUE TITLE
Subscription not being renewed.

### ISSUE THREAD

**Issue by tania010** [kylierst/MSO_E5_Dev_AutoRenew#19]
Having the same issue as some of the others in this thread:
#15 

Subscription days counting down:
![sub Capture](https://user-images.githubusercontent.com/51423213/235326958-e831b323-6103-40b6-94b9-b440be5a1bc9.PNG)

workflows are working
![actions Capture](https://user-images.githubusercontent.com/51423213/235327009-82586d28-5ab2-4e7c-8fda-4551ae41f689.PNG)

didn't know about linking github account to 365 before (_**this should be in the setup steps**_) so linked it today
![mail Capture](https://user-images.githubusercontent.com/51423213/235327098-ade373e0-a904-4387-934d-56cb502eb624.PNG)

waited for a few hours after linking accounts, before posting this issue here, days left is still at 87

**Comment by kylierst** [comment]
The subscription is renewed roughly every 40~70 days in my case. You should receive and email when it renews.

**Comment by tania010** [comment]
Is there a way to check that this application is doing what it's supposed to be doing, to make sure that the subscription DOES get renewed when the time comes?
I mean check it on microsoft's side. Since the link in the setup steps: https://developer.microsoft.com/en-us/graph/graph-explorer/preview leads to a blank white page with "Starting the Microsoft Graph Explorer..." but nothing ever loads doesn't matter how long i leave it open
![graph Capture](https://user-images.githubusercontent.com/51423213/235357147-cbd90c01-e773-40b7-9d74-8bfc48cb0b73.PNG)

**Comment by ropepop** [comment]
did my own research and so far there is no way to know whether it’s working or not, until you actually get the letter of happiness from Microsoft that your subscription is renewed, as a commentator already said

**Comment by tania010** [comment]
I can confirm that the subscription WAS renewed. Still don't know of a way, anyone setting this up, can check if the script is actually working.
