### ISSUE TITLE
Have this Git own youtube video?

### ISSUE THREAD

**Issue by noncaptureaub1** [kylierst/MSO_E5_Dev_AutoRenew#2]
is there any youtube video for this ?
because this tutorial  is very difficult for me (may be my noob).
please in video sir

**Comment by kylierst** [comment]
I would try to come up with a thorough tutorial in the next few days in my free time. Stay tuned

**Comment by noncaptureaub1** [comment]
thanks sir i will wait and if finished ,please share link and your channel sir.

**Comment by Doktor-X** [comment]
Yes you need to make video or modify reading instructions, i cant set this up i cant get refresh token

**Comment by kylierst** [comment]
> Yes you need to make video or modify reading instructions, i cant set this up i cant get refresh token

Try to follow the new instructions. I cleaned it up. Sorry but I had to cancel making a video tutorial of this on youtube as Microsoft might take this down.

**Comment by Doktor-X** [comment]
> > Yes you need to make video or modify reading instructions, i cant set this up i cant get refresh token
> 
> Try to follow the new instructions. I cleaned it up. Sorry but I had to cancel making a video tutorial of this on youtube as Microsoft might take this down.

I have now manage to get it working fine, and i have found why i did not manage to get refresh token step working, when i copy/paste token i was one number short i did not copy entire string (i have used my phone to setup all this up)

**Comment by kylierst** [comment]
> > > Yes you need to make video or modify reading instructions, i cant set this up i cant get refresh token
> > 
> > 
> > Try to follow the new instructions. I cleaned it up. Sorry but I had to cancel making a video tutorial of this on youtube as Microsoft might take this down.
> 
> I have now manage to get it working fine, and i have found why i did not manage to get refresh token step working, when i copy/paste token i was one number short i did not copy entire string (i have used my phone to setup all this up)

Nice!

**Comment by AndreMuhamed** [comment]
> > Так, вам потрібно створити відео або змінити інструкції для читання, я не можу це налаштувати, я не можу отримати маркер оновлення
> 
> Спробуйте слідувати новим інструкціям. Я почистив це. Вибачте, але мені довелося скасувати створення відеоуроку про це на YouTube, оскільки Microsoft може це видалити.

and you can make the video private, only the parcel, or upload it to some cloud storage.
