### ISSUE TITLE
NameError: name 'refresh_token' is not defined

### ISSUE THREAD

**Issue by seth-aung** [kylierst/MSO_E5_Dev_AutoRenew#21]
I don't know what to do about this error. I tried so many times and this error won't go away. Please point me what I was wrong.  Thank you so much.

![image](https://user-images.githubusercontent.com/94091504/236797999-ac6c523a-8762-4776-b43a-5895e902c58e.png)

**Comment by quinnzbellz** [comment]
what ended up fixing it?

**Comment by seth-aung** [comment]
![Screenshot 2023-05-16 064513](https://github.com/kylierst/MSO_E5_Dev_AutoRenew/assets/94091504/34e9bd6b-f5b7-4be1-9d88-76e48fbe447e)
Yes, I made one mistake because I confused when reading read-me.

**Comment by dolodi** [comment]
Do you have to make repository secrets or vaariables ?

**Comment by seth-aung** [comment]
> Do you have to make repository secrets or vaariables ?
> 

Just secret.
