### ISSUE TITLE
Auth Error 

### ISSUE THREAD

**Issue by dsakura** [kylierst/MSO_E5_Dev_AutoRenew#22]
Step 5 error:
```
Error: Auth Error
Code: ""
Description: No code returned by remote server
```

Pointers to the locations on the d azure website would help, their website is very confusing. But well, the app ID I found is the one found in overview > Application ID (client), and the secret in overview > client credentials.
Permissions under: Manage > API Permissions and clicked Grant Admin Consent to MSFT.
Some terms may be wrong because my native language is not English.

Many thanks!

**Comment by RWTighnari** [comment]
Make sure this option is selected in the Azure application registration, or try to turn off the firewall, hoping I can help you.![image](https://github.com/kylierst/MSO_E5_Dev_AutoRenew/assets/134622706/d8703177-bf77-4100-b171-47ed5b2b1a5d)

**Comment by dsakura** [comment]
The problem was the supported account type, indeed. Now it's running fine, thank you very much, again! o/
