### ISSUE TITLE
Cann't find App Permission?

### ISSUE THREAD

**Issue by sennoncap** [kylierst/MSO_E5_Dev_AutoRenew#25]
i cannot find app permissions( files.read.all, files.readwrite.all, sites.read.all, sites.readwrite.all, user.read.all, user.readwrite.all, directory.read.all, directory.readwrite.all, mail.read, mail.readwrite, mailboxsetting.read, and mailboxsetting.readwrite.) 

![1 back](https://github.com/kylierst/MSO_E5_Dev_AutoRenew/assets/118154316/9a287b7a-9e6e-4481-9388-c5193a930a9f)

how to do that sir? and is that any youtube video for this...

**Comment by kylierst** [comment]
Choose Microsoft Graph
![image](https://github.com/kylierst/MSO_E5_Dev_AutoRenew/assets/22324149/56cb26c4-24bc-4d01-b388-bfd5d788efea)

Then Delegated Permissions. You can start searching there
![image](https://github.com/kylierst/MSO_E5_Dev_AutoRenew/assets/22324149/a79ac868-1503-4a31-9e67-ee0a947a5632)
