### ISSUE TITLE
Workflow failing?

### ISSUE THREAD

**Issue by LatroM69** [kylierst/MSO_E5_Dev_AutoRenew#27]
I am getting the following error when it is at "Test API" during the workflow. 
File "/home/runner/work/MSO_E5_Dev_AutoRenew/MSO_E5_Dev_AutoRenew/temp.py", line 11
    ***
        ^
SyntaxError: invalid syntax
Error: Process completed with exit code 1.

Any idea what's going on?

**Comment by kylierst** [comment]
Try to get a new refresh token and re-setup you github secrets

**Comment by messiasjafe** [comment]
hello,
did you manage to solve the problem?
I'm in the same situation.
