### ISSUE TITLE
Subscription not updated even after 60 days.

### ISSUE THREAD

**Issue by SiddheshDongare** [kylierst/MSO_E5_Dev_AutoRenew#30]
![Screenshot 2023-07-18 205904](https://github.com/kylierst/MSO_E5_Dev_AutoRenew/assets/70208548/da1f6841-43f9-44a4-ab05-68ba17350d2d)
It's been about 2 months, but my subscription hasn't been updated yet. Github Actions shows all tasks being completed properly. Is this normal?

**Comment by kylierst** [comment]
![image](https://github.com/kylierst/MSO_E5_Dev_AutoRenew/assets/22324149/1ef1bf84-fe3e-4b94-b998-0c8fbc0c955d)
Rest assured it still works. Just make sure Github is connected in Microsoft Developer dashboard and occasionally check Git Actions if it runs properly

**Comment by cybermyran** [comment]
"Just make sure Github is connected in Microsoft Developer dashboard" 

I couldn't find anyway to check this. Can someone share the link of the dashboard?
