### ISSUE TITLE
Not a issue but a stupid doubt.

### ISSUE THREAD

**Issue by cybermyran** [kylierst/MSO_E5_Dev_AutoRenew#34]
In your second step of your guide, you mention saving Application ID and Secret. But I couln't find any Secret in the azure portal. All I can see is Display name, Application (client) ID, Object ID. Or did you mean creating a Client Secret from the 'Certificates and Secrets' tab ?
![IMG_20230729_195014](https://github.com/kylierst/MSO_E5_Dev_AutoRenew/assets/126302194/8c407bd8-9c49-4b52-9349-d608d1e26e70)

**Comment by RecodeLiner** [comment]
second

**Comment by cybermyran** [comment]
> second, in 'Certificates and Secrets' tab

And in the fifth step, it says to enter the id and secret along with the rclone command. The secret meant here is the Secret 'Value', right ? Because there is both Secret ID and Secret Value and I am confused :\
