### ISSUE TITLE
SyntaxError: invalid syntax Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by bequbed** [kylierst/MSO_E5_Dev_AutoRenew#40]
I am getting this error:

File "/home/runner/work/MSO_E5_Dev_AutoRenew/MSO_E5_Dev_AutoRenew/temp.py", line 11
***
^
SyntaxError: invalid syntax
Error: Process completed with exit code 1.

Any suggestions on how I can rectify it?

**Comment by benjaminmorozov** [comment]
Hi, the error is caused by incorrect repo secrets. Check these things:

1. Actions > Secrets - you're supposed to add a secret, not a variable!
2. The secrets are to be formatted in this way:

Name:
CONFIG_ID
Value:
client_id=r'your application_id'

3. Re-add the secrets and retry. If you're still getting the same error, try to generate a new refresh token and update it.
4. Last solution would be to delete the app in azure active directory and remake it.

**Comment by dsakura** [comment]
this error started some days ago.. nothing changed. Was there an update that asks for a new formatting of the secret? Thanks


```
Run echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
Traceback (most recent call last):
  File "/home/runner/work/MSO_E5_Dev_AutoRenew/MSO_E5_Dev_AutoRenew/temp.py", line 83, in <module>
    main()
  File "/home/runner/work/MSO_E5_Dev_AutoRenew/MSO_E5_Dev_AutoRenew/temp.py", line 62, in main
    access_token = get_access_token(refresh_token, client_id, client_secret)
  File "/home/runner/work/MSO_E5_Dev_AutoRenew/MSO_E5_Dev_AutoRenew/temp.py", line 55, in get_access_token
    refresh_token = jsontxt['refresh_token']
KeyError: 'refresh_token'
Error: Process completed with exit code [1](https://github.com/dsakura/MSO_E5_Dev_AutoRenew/actions/runs/6098452293/job/16548307170#step:6:1).
```

**Comment by benjaminmorozov** [comment]
No, no that I read of - but I think the refresh tokens can expire too - did you try redoing the rclone part and reentering all the values?

**Comment by benjaminmorozov** [comment]
No, no that I know of any. The key_error is returned in this way. The python script opens the oauth microsoft url to login into the app and generate new refresh_tokens and access_tokens.
To achieve that, it supplies a refresh_token, client_id and a client_secret that's loaded from the repo secrets. It then tries to convert the finished response from the oauth into json. It searches for a "refresh_token" but it doesn't exist so it throws an exception.

The reason for "refresh_token" not existing would be a 403 Forbidden response, which would only contain the error code and not the expected values. It's most likely that. A solution would be to redo the rclone steps to generate a new refresh_token. Using rclone would pretty much confirm if the app_id and secret are correct. Reenter them into the secrets in the format I mentioned above.

If THAT doesn't work then someone also fixed this by redoing all the app steps by basically removing the app and creating a new one.

**Comment by doomwithdon** [comment]
Yep this exact error started just 2 days ago for me too. Was working perfectly fine earlier.

**Comment by bequbed** [comment]
![Screenshot 2023-09-07 140537](https://github.com/kylierst/MSO_E5_Dev_AutoRenew/assets/107822319/1915387e-b68a-443e-84da-df408dfc71fe)

 I am getting this error after getting a new refresh token  from JSON Handler

**Comment by bequbed** [comment]
Nevermind, I had to run the action again by deselecting and selecting star again. Thanks guys for your help :)

**Comment by doomwithdon** [comment]
I registered a new app and followed all steps again. started working once again. Thanks

**Comment by bequbed** [comment]
Suffice to close this issue. Would be handy to others who might come across this issue in the future.
